# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.IntegerField()),
                ('choice_A', models.CharField(max_length=200)),
                ('choice_B', models.CharField(max_length=200)),
                ('choice_C', models.CharField(max_length=200)),
                ('choice_D', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('right_answer', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
