# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0002_auto_20160109_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_type', models.IntegerField(default=1, verbose_name='Question Type (1-5)')),
                ('choice_A', models.CharField(max_length=200)),
                ('choice_B', models.CharField(max_length=200)),
                ('choice_C', models.CharField(max_length=200)),
                ('choice_D', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('wechat', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='judgequestion',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name='Question Type (1-5)'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name='Question Type (1-5)'),
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='right_answer',
            field=models.BooleanField(default=False, verbose_name='Right Or False'),
        ),
    ]
