# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0003_auto_20160114_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='njdz_wechat.QuestionType'),
        ),
    ]
