# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0006_auto_20160114_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='question_type',
            field=models.IntegerField(default=1, verbose_name='Question Type (1-5)'),
        ),
    ]
