# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0009_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
    ]
