# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0010_auto_20160114_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='is_choice',
            field=models.BooleanField(default=True, verbose_name='Is ChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='judgequestion',
            name='is_judge',
            field=models.BooleanField(default=True, verbose_name='Is JudgeQuestion'),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='is_multichoice',
            field=models.BooleanField(default=True, verbose_name='Is MultiChoiceQuestion'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Exam Type'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='url',
            field=models.CharField(max_length=20, verbose_name='Exam URL'),
        ),
    ]
