# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('njdz_wechat', '0013_auto_20160226_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_type',
        ),
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.CharField(default=datetime.datetime(2016, 3, 3, 15, 3, 27, 202000, tzinfo=utc), max_length=200, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='work_type',
            field=models.CharField(default=datetime.datetime(2016, 3, 3, 15, 3, 32, 785000, tzinfo=utc), max_length=100, verbose_name='Work Type'),
            preserve_default=False,
        ),
    ]
